#!/bin/sh

tmpf=/tmp/checkports.$$
gn=$HOME/bin/i386-apple-darwin/growlnotify

$gn -n port -m 'Checking for outdated ports' 'Ports'

/opt/local/bin/port outdated > $tmpf
if grep 'No installed ports are outdated' $tmpf > /dev/null
then
	:
else
	cat $tmpf | $gn -n port -s 'Outdated Ports'
fi

rm $tmpf
