#!/usr/bin/env python

import sys
import subprocess

import gitaggregates

def read_tag(t):
    args = ['git', 'cat-file', 'tag', t]
    sub = subprocess.Popen(args, stdout=subprocess.PIPE, close_fds=True)

    rv=None
    for l in sub.stdout:
        if rv is not None:
            rv.append(l)
        elif l.strip() == '':
            rv = []

    return ''.join(rv)

def emit(prev, r, f=sys.stdout):
    tagdesc = read_tag(r)

    c = gitaggregates.Contributors([prev + '..' + r])
    vdesc = "Changes from release %s to %s" % (prev, r)
    if not prev:
        vdesc = "Release " + r
    f.write("<h2>%s</h2>\n" % (vdesc))
    f.write("""<div><img class="pie" src="%s" alt="contributors"/>"""
            % (c.to_gchart()))
    f.write("<pre>%s</pre></div>" % tagdesc)

if __name__ == '__main__':

    if not sys.argv[1:]:
        sys.stderr.write("Need to list some tag objects.\n")
        sys.exit(1)

    print """<html>
<head>
    <title>Changelog</title>
    <style type="text/css">
        .pie {
            float: right;
        }
        h2 {
            clear: both;
        }
    </style>
</head>

<body>
"""

    prev = ''

    pairs = []

    for r in sys.argv[1:]:
        pairs.append((prev, r))
        prev = r

    for prev, r in reversed(pairs):
        emit(prev, r)

    print "</body></html>"
