#!/bin/sh

git clean -dfx
./make.bash

for f in runtime/rt0_*.s
do
    b=`basename $f .s`
    os=`echo $b | awk -F_ '{print $2}'`
    arch=`echo $b | awk -F_ '{print $3}'`

    env GOOS=$os GOARCH=$arch ./make.bash --no-clean
done
