#!/bin/sh

RSH=ssh

for i in "$@"
do
	echo "Playing $i"
	$RSH butterfly "mpg123 -" < "$i" &
	PID=$!
	trap "kill $PID" INT
	wait $PID
	trap INT
	# Wait a second so we can kill the script if we want
	sleep 1
done
