#!/bin/sh
 
p=`pwd`
binname=`basename $p`

for p in 386 arm amd64
do
    for o in linux darwin windows
    do
        env GOARCH=$p GOOS=$o CGO_ENABLED=0 go build -v -o $binname/$binname.$o.$p &
    done
done

wait
