#!/usr/bin/env python2.2

# Reprint a file (get the line endings right)

import sys

f=open(sys.argv[1])

s=f.read(4096)
while s != '':
	s=s.replace('\r', '\n')
	s=s.replace('\n\n', '\n')
	sys.stdout.write(s)
	s=f.read(4096)

f.close()
print ''
