#!/bin/sh

ITUNES="/Volumes/bag/itunes/Music/"

rsync "$@" -varltpogSe ssh --progress --stats \
    --delete --delete-excluded --exclude .DS_Store \
    --exclude=.Trashes/ \
    --exclude=Podcasts/ \
    --exclude=Coverville/ \
    --exclude=.Spotlight-V100 \
    "$ITUNES" menudo:/Volumes/terror/media/music/dustin/

# --exclude="*.m4p" --exclude="*.m4a" \
