#!/bin/sh

ITUNES="/Volumes/bag/itunes/"

rsync "$@" -varltpogS --progress --stats \
	--delete --delete-excluded --exclude .DS_Store \
	--exclude=Podcasts/ \
	--exclude=Coverville/ \
    --exclude=.Spotlight-V100 \
    "$ITUNES" purple::${USER}mp3w/

# --exclude="*.m4p" --exclude="*.m4a" \
