#!/bin/sh

umask 22

TOP=`pwd`
PATHS=""

if [ $# -gt 0 ]
then
	PATHS="$@"
else
	PATHS=`find * -type d -name _darcs | xargs -n 1 dirname`
fi

for i in $PATHS
do
	if [ -f "$i/_darcs/prefs/defaultrepo" ]
	then
		cd "$i"
		echo "Pulling $i"
		darcs pull -v -a
		cd "$TOP"
	fi
done
