#!/bin/sh
# Copyright (C) 2004 Aaron Bentley
#
# See the file "COPYING" for further information about
# the copyright and warranty status of this work.

. "$abadir/aba-lib"
cmd_exec()
{
  if [ -z "$1" ]; then
    if [ -f ~/.aba/aliases ]; then
      cat ~/.aba/aliases
    fi
  else
    echo $1 >> ~/.aba/aliases
  fi
}
cmd_desc()
{
  echo '                       alias : add or view aliases'
}
cmd_help()
{
  echo "With no parameters, lists current aliases.  If an alias is provided, adds it."
}
cmd_ext_help()
{
  echo "Aliases should be of the form foo=bar, and should not include ^ or \$."
}
aba_run "$@"
# arch-tag: alias by Aaron Bentley (20:14 Feb 1, 2004)
