#!/bin/sh
# Copyright (C) 2004 Aaron Bentley
#
# See the file "COPYING" for further information about
# the copyright and warranty status of this work.

. "$abadir/aba-lib"
cmd_exec()
{
  aba tag-this $1
  aba sync-tree $1--base-0
  aba set-tree-version $1
}
cmd_desc()
{
  echo '                 branch-this : branches the current tree to a new tag'
}
cmd_help()
{
  echo "This creates a new tag from the current tree, then sets the current tree to"
  echo "that tag.  No options are available."
}
cmd_ext_help()
{
echo -n
}
aba_run "$@"
# arch-tag: branch-this by Aaron Bentley (11:40 Jan 28, 2004)
