#!/bin/sh
# Copyright (C) 2004 Aaron Bentley
#
# See the file "COPYING" for further information about
# the copyright and warranty status of this work.

. "$abadir/aba-lib"
cmd_exec()
{
   tla delta --report -n "$@"
}
cmd_desc()
{
  echo '                    diff-rev : alias for delta --report -n'
}
cmd_help()
{
  echo "Displays the difference between two revisions.  Alias for alias for "delta --report -n"."
}
cmd_ext_help()
{
   echo -n
}
aba_run "$@"
# arch-tag: diff-rev by Aaron Bentley (23:19 Jan 28, 2004)
