#!/bin/sh
# Copyright (C) 2004 Aaron Bentley
#
# See the file "COPYING" for further information about
# the copyright and warranty status of this work.
unset ABAFILTER
export ABAFILTER

. "$abadir/aba-lib"
cmd_exec()
{
  if [ -z "$EDITOR" ]; then
    echo '$EDITOR not set'
    exit 1
  fi
  if file=`tla make-log`; then
    $EDITOR $file
  fi
}
cmd_desc()
{
  echo '                        elog : shortcut for $EDITOR `tla make-log`'
}
cmd_help()
{
    cat <<EOH
shortcut for \$EDITOR \`tla make-log\`.  
usage: $abaname elog

This works just like \$EDITOR \`tla make-log\`, except that it handles errors
better.
EOH
}
cmd_ext_help()
{
    cat <<EOH
EOH
}	
aba_run "$@"

# arch-tag: elog by Aaron Bentley (12:17 Jan 15, 2004)
