#! /bin/sh
## Copyright (C) 2004 Aaron Bentley
##
## See the file "COPYING" for further information about
## the copyright and warranty status of this work.

. "$abadir/aba-lib"

# executes the command ("$@" are the arguments after the command name)
cmd_exec()
{
  diff -u $(tla file-find $1 $(aba_full_revision $2)) $(tla file-find projectlanguage.cpp $(aba_full_revision $3))
}

# one-liner description for aba help
cmd_desc()
{
    aba_desc $(basename $0) "Compare two revisions of a file"
}

# short help for aba command -h, --help
cmd_help()
{
    cat <<EOH
Description...
usage: $abaname $(basename $0) file [revision] [revision]

Omitted revisions will default to the tree revision.  Patchlevels are fine.
EOH
}

# extended help for aba command -H or aba help command
cmd_ext_help()
{
    cat <<EOH
EOH
}	

aba_run "$@"
#  arch-tag: file-diff-rev by Aaron Bentley  (11:40 May 12 2004)
