#! /bin/sh
## Copyright (C) 2004 Aaron Bentley
##
## See the file "COPYING" for further information about
## the copyright and warranty status of this work.

. "$abadir/aba-lib"

# executes the command ($* are the arguments after the command name)
cmd_exec()
{
   if [ -z "$1" ]; then
      echo Please provide a file name
      exit 1
   fi
   echo -n "$(tla id $1|cut -f 2)	"
   stat --format="dev=%d:ino=%i:mtime=%Y:size=%s" $1
}

# one-liner description for aba help
cmd_desc()
{
  aba_desc gen-sig "generates an inode-sig for a file"
}

# short help for aba command -h, --help
cmd_help()
{
   cat <<EOT
usage: aba gen-sig filename

Generates the inode signature for a given file.

EOT
}

# extended help for aba command -H or aba help command
cmd_ext_help()
{
echo -n
}	

aba_run "$@"
# arch-tag: gen-sig by Aaron Bentley  (15:06 Feb 11 2004)
