#!/bin/sh

. "$abadir/aba-lib"

cmd_exec () {
    options="dir|d=f style|s=s help|h=f H=f"
    . "$abadir/getopt"

    if test -n "$style" -a \! -r "$HOME/.arch-params/=$style"; then
	echo "* Unknown style: $style ($HOME/.arch-params/=$style does not exist" >&2
	exit 1
    fi

    echo "* Initialising the tree"
    tla init-tree "$@" || exit $?
    style=${style:-method}
    if [ -r "$HOME/.arch-params/=tagging-$style" ]; then
	echo "* Installing $HOME/.arch-params/=tagging-$style as id-tagging-method"
	cp "$HOME/.arch-params/=tagging-$style" "{arch}/=tagging-method"
    fi
}

cmd_help () {
    aba_omit_last 1 tla init-tree -h
    cat <<EOH
  -s, --style ST use =tagging-ST as template for tagging method.

EOH
}

cmd_ext_help () {
    cat <<EOH
Initialize DIR as a new project tree.

An empty patch-log for VERSION will be created, and VERSION
will be made the default location for check-ins.

~/.arch-params/=tagging-method will be used as default
id-tagging-method, if it exists.

EOH
}

cmd_desc () {
    :
}

aba_run "$@"
# arch-tag: 18166a7a-df84-4540-afe3-4f467f2fbb86
