#! /bin/sh
## Copyright (C) 2004 Aaron Bentley
##
## See the file "COPYING" for further information about
## the copyright and warranty status of this work.

. "$abadir/aba-lib"

# executes the command ("$@" are the arguments after the command name)
cmd_exec()
{
   if [ -n "$1" ]; then
     version=$1
   else
     version=`tla tree-version`
   fi
   echo $version--`tla revisions $version| tail -n 1`
}

# one-liner description for aba help
cmd_desc()
{
echo '             latest-revision : Outputs the latest revision of a package'
}

# short help for aba command -h, --help
cmd_help()
{
   echo "Usage: aba latest-revision [package--version]"
}

# extended help for aba command -H or aba help command
cmd_ext_help()
{
   echo -n
}	

aba_run "$@"
# arch-tag: latest-revision by Aaron Bentley (13:59 Feb 4, 2004)
