#! /bin/sh
## Copyright (C) 2004 Aaron Bentley
##
## See the file "COPYING" for further information about
## the copyright and warranty status of this work.

. "$abadir/aba-lib"

# executes the command ($* are the arguments after the command name)
cmd_exec()
{
  if [ -n "$1" ]; then
    tla library-config $*
  else
    for lib in `tla my-revision-library`; do
      tla library-config $lib
    done;
  fi
}

# one-liner description for aba help
cmd_desc()
{
   echo -n
}

# short help for aba command -h, --help
cmd_help()
{
   echo -n
   tla library-config -h;
   echo aba version: lists settings for all libraries if no arguments 
   echo
}

# extended help for aba command -H or aba help command
cmd_ext_help()
{
   echo -n
   tla library-config -H;
   echo aba version: lists settings for all libraries if no arguments 
   echo
}	

aba_run_tlawrap "$@"
# arch-tag: library-config by Aaron Bentley  (10:43 Feb 08 2004)
