#! /bin/sh
## Copyright (C) 2004 Aaron Bentley
##
## See the file "COPYING" for further information about
## the copyright and warranty status of this work.

. "$abadir/aba-lib"

# executes the command ("$@" are the arguments after the command name)
cmd_exec()
{
for rev in $(tla library-revisions -f $1); do
  echo Removing $rev
  tla library-remove $rev
done
}

# one-liner description for aba help
cmd_desc()
{
    aba_desc $(basename $0) "Remove all library revisions for a given version"
}

# short help for aba command -h, --help
cmd_help()
{
    cat <<EOH
Remove all revisions for a given version from the revlib
usage: $abaname $(basename $0) version

This will remove all revisions for a given version from the library.  Its
reason for existence was to prevent the partial-mirror command from mirroring
old, uninteresting versions.

EOH
}

# extended help for aba command -H or aba help command
cmd_ext_help()
{
    cat <<EOH
EOH
}	

aba_run "$@"
#  arch-tag: library-remove-version by Aaron Bentley  (11:00 Apr 26 2004)
