#! /bin/sh
## Copyright (C) 2004 Aaron Bentley
##
## See the file "COPYING" for further information about
## the copyright and warranty status of this work.

. "$abadir/aba-lib"

# executes the command ("$@" are the arguments after the command name)
cmd_exec()
{
  tla commit "$@"
  if [ $? -ne 0 ]; then
    exit;
  fi
  tv=$(tla tree-version)
  if [ $? -ne 0 ]; then
    exit;
  fi
  archive=$(tla parse-package-name --arch $tv)
  version=$(tla parse-package-name --package-version $tv)
  tla archive-mirror $archive $version
}

# one-liner description for aba help
cmd_desc()
{
    aba_desc $(basename $0) "commits and mirrors a revision"
}

# short help for aba command -h, --help
cmd_help()
{
    cat <<EOH
commits and mirrors a revision
usage: $abaname $(basename $0) [OPTIONS]

Accepts all commit options, but --dir should not be used, since mirroring
is done according to tree-version.

All revisions in the current project tree are mirrored, not only the one
committed.
EOH
}

# extended help for aba command -H or aba help command
cmd_ext_help()
{
    cat <<EOH
EOH
}	

aba_run "$@"

# arch-tag: mcommit by Aaron Bentley  (12:20 Feb 18 2004)
