#!/bin/sh
# Copyright (C) 2004 Aaron Bentley
#
# See the file "COPYING" for further information about
# the copyright and warranty status of this work.
unset ABAFILTER
export ABAFILTER

. "$abadir/aba-lib"
cmd_exec()
{
  sourcefile=`tla tree-root 2> /dev/null`/++merge-source 
  if [ $? -ne 0 ]; then
      echo "merge: not in project tree ($(pwd))" >&2
      exit 2;
    exit 1
  fi
  if [ -n "$1" ]; then
    sourcever=$1;
    sourcetype="[supplied]"
  elif [ -f $sourcefile ] ; then
    sourcever=$(cat $sourcefile)
    sourcetype="[from ++merge-source]"
  else
    treesource=$(aba_tree_source)
    status=$?;
    # always false
    if [ $status -eq 2 ]; then
      echo "merge: not in project tree ($(pwd))" >&2
      exit 2;
    fi
    if [ $status -ne 0 ]; then
      echo "aba merge: Unable to find $sourcefile" or tag source >&2
      exit 1;
    fi
    sourcever="$(tla parse-package-name -a $treesource)/$(tla parse-package-name --package-version $treesource)"
    sourcetype="[from tag-source]"
  fi
  aba_no_changes
  for source in $sourcever; do
  echo "* merge source $sourcetype: $source"
  tla star-merge $source;
  if [ $? -ne 0 ]; then 
    tla log-for-merge >> $(tla make-log)
    echo "Problems encountered during merge (see aba conflicts)" >&2
    exit 1;
  fi
  if ! tla changes > /dev/null; then
    aba emlog
    exit 0
  else
    echo "* tree is already up to date with $source"
  fi
  done
}
cmd_desc()
{
  echo '                       merge : star-merge with ++merge-source, then edit log'
}
cmd_help()
{
cat <<EOH
performs an automated star-merge
usage: $abaname merge [version]

Selects the source version from (in order of selection):
1. The supplied version
2. The contents of ++merge-source in the project tree root
3. The tag-source of the project tree, as determined from the patch-logs

It will not perform the merge if there are uncommitted changes in the tree.

If there are conflicts, it will warn that problems were encountered.

Otherwise, if the merge changed the tree, it will do $abaname emlog to produce
a log message.

If the merge was successfully applied, but did not change the tree, it will say so.

++merge-source may contain multiple merge sources, separated by whitespace.
In this case, each source will be tried in order, stopping at the first merge
that actually changes the tree.

EOH
}
cmd_ext_help()
{
  echo -n
}
aba_run "$@"
# arch-tag: merge by Aaron Bentley (11:15 Jan 26, 2004)
