#! /bin/sh
## Copyright (C) 2004 Aaron Bentley
##
## See the file "COPYING" for further information about
## the copyright and warranty status of this work.

. "$abadir/aba-lib"

# executes the command ("$@" are the arguments after the command name)
cmd_exec()
{
  aba_merge_source $1
  for source in $sourcever; do
    tla missing -sf $source
  done
}

# one-liner description for aba help
cmd_desc()
{
    aba_desc $(basename $0) "Does \"tla missing -sf\" for merge sources"
}

# short help for aba command -h, --help
cmd_help()
{
    cat <<EOH
Does "tla missing -sf" for merge sources
usage: $abaname $(basename $0) [VERSION]

Determines merge-sources the same way as "merge" (argument, =partner-versions,
++merge-source) and lists missing revisions by full name with summaries

EOH
}

# extended help for aba command -H or aba help command
cmd_ext_help()
{
    cat <<EOH
EOH
}	

aba_run "$@"
#  arch-tag: missing-merge by Aaron Bentley  (11:25 May 31 2004)
