#! /bin/sh
## Copyright (C) 2004 Aaron Bentley
##
## See the file "COPYING" for further information about
## the copyright and warranty status of this work.

. "$abadir/aba-lib"

# executes the command ("$@" are the arguments after the command name)
cmd_exec()
{
    ver=$2
    if [ -z $2 ]; then
      ver=$(tla tree-version)
    fi

    dir=$(tla library-find $1)
    tla missing -s -d $dir $ver
}

# one-liner description for aba help
cmd_desc()
{
    aba_desc $(basename $0) "Inverted version of missing"
}

# short help for aba command -h, --help
cmd_help()
{
    cat <<EOH
Inverted version of missing
usage: $abaname $(basename $0) REVISION [VERSION]

Shows which revisions of VERSION are missing from REVISION.  Version defaults
to the current tree-version.

EOH
}

# extended help for aba command -H or aba help command
cmd_ext_help()
{
    cat <<EOH
EOH
}	

aba_run "$@"
#  arch-tag: missing-from by Aaron Bentley  (23:04 Jun 04 2004)
