#!/bin/sh
# Copyright (C) 2004 Aaron Bentley
#
# See the file "COPYING" for further information about
# the copyright and warranty status of this work.

. "$abadir/aba-lib"

cmd_exec()
{
  tla my-revision-library "$@"
}
cmd_desc()
{
  echo '                  my-library : alias for my-revision-library'
}
cmd_help()
{
   tla my-revision-library -h|sed "s/tla my-revision-library/$abaname my-library/g";
}
cmd_ext_help()
{
   tla my-revision-library -H|sed "s/tla my-revision-library/$abaname my-library/g";
}

aba_run_tlawrap "$@"


# arch-tag: my-library by Aaron Bentley (12:18 Jan 15, 2004)
