#! /bin/sh
## Copyright (C) 2004 Aaron Bentley
##
## See the file "COPYING" for further information about
## the copyright and warranty status of this work.

. "$abadir/aba-lib"

# executes the command ($* are the arguments after the command name)
cmd_exec()
{
  options="library full"
  . "$abadir/getopt"
  if [ -n "$library" ]; then
    catcmd="library-categories"
    branchcmd="library-branches"
  else
    catcmd="categories"
    branchcmd="branches"
  fi
  if [ -n "$1" ]; then
    archive="$1/";
  else
    archive="";
  fi
  if [ -n "$full" ]; then
    prefix="$archive"
  fi
  for cat in `tla $catcmd $1`; do
    for package in $(tla $branchcmd $archive$cat); do
      echo $prefix$package
    done;
  done;
}

# one-liner description for aba help
cmd_desc()
{
   aba_desc packages Lists all packages in the current archive 
}

# short help for aba command -h, --help
cmd_help()
{
   cat <<EOT
usage: aba packages [archive]

  --library         search revision libraries instead of archives
  --full            show the full category name

List all the packages in the given archive.  If no archive is given, uses the
default archive.

EOT
}

# extended help for aba command -H or aba help command
cmd_ext_help()
{
   echo -n
}	

aba_run "$@"
# arch-tag: packages by Aaron Bentley  (09:15 Feb 10 2004)
