#! /bin/sh
## Copyright (C) 2004 Aaron Bentley
##
## See the file "COPYING" for further information about
## the copyright and warranty status of this work.

. "$abadir/aba-lib"

# executes the command ($* are the arguments after the command name)
cmd_exec()
{
  options="library full revisions"
  . "$abadir/getopt"
  if [ -n "$library" ]; then
    library="--library"
    vercmd="library-versions"
  else
    vercmd="versions"
  fi
  if [ -n "$1" ]; then
    archive="$1/";
  else
    archive="";
  fi
  if [ -n "$full" ]; then
    prefix="$archive"
  fi

  for cat in `aba packages $library $1`; do
    for packageversion in $(tla $vercmd $archive$cat); do
      if [ -z "$revisions" ]; then
        echo $prefix$packageversion
      else
        if [ -n "$(tla library-revisions $archive$packageversion)" ]; then
          echo $prefix$packageversion
	fi
      fi
    done;
  done;
}

# one-liner description for aba help
cmd_desc()
{
   aba_desc package-versions Lists all package versions in an archive 
}

# short help for aba command -h, --help
cmd_help()
{
   cat <<EOT
usage: aba package-versions [archive]

  --library         search revision libraries instead of archives
  --full            show the full version name
  --revisions       show only versions that have revisions in the library

List all the package versions in the given archive.  Defaults to 
my-default-archive.

EOT
}

# extended help for aba command -H or aba help command
cmd_ext_help()
{
   echo -n
}	

aba_run "$@"
# arch-tag: package-versions by Aaron Bentley  (12:03 Feb 10 2004)
