#! /bin/sh
## Copyright (C) 2004 Aaron Bentley
##
## See the file "COPYING" for further information about
## the copyright and warranty status of this work.

. "$abadir/aba-lib"

# executes the command ("$@" are the arguments after the command name)
cmd_exec()
{
    if [ -z "$1" ]; then
	echo "Please enter a target version"
	exit
    fi
    new_version=$1
    if [ -n "$2" ]; then
      old_version=$2
    else
      old_version=$(aba_fqversion $(aba_tree_source))
    fi
    delta_to=$(tla logs -f -r | head -n 1)
    delta_from=$(tla logs -f -r $old_version| head -n 1)
    tla tag -S --no-cacherev $old_version $new_version
    aba_change_version $new_version
    tla apply-delta $delta_from $delta_to
}

# one-liner description for aba help
cmd_desc()
{
    aba_desc $(basename $0) "Create a new version with a different tree-source"
}

# short help for aba command -h, --help
cmd_help()
{
    cat <<EOH
Create a new version with a different tree-source
usage: $abaname $(basename $0) TARGET-VERSION [BASIS]

If the basis is supplied, it may be a version or revision if not supplied, the
tag-source is used.
EOH
}

# extended help for aba command -H or aba help command
cmd_ext_help()
{
    cat <<EOH
EOH
}	

aba_run "$@"
#  arch-tag: rebase by Aaron Bentley  (23:06 Jun 05 2004)
