#! /bin/sh
## Copyright (C) 2004 Aaron Bentley
##
## See the file "COPYING" for further information about
## the copyright and warranty status of this work.

. "$abadir/aba-lib"

# executes the command ($* are the arguments after the command name)
cmd_exec()
{
   tla changes --link > /dev/null
}

# one-liner description for aba help
cmd_desc()
{
  aba_desc relink "alias for 'tla changes --link'"
}

# short help for aba command -h, --help
cmd_help()
{
   cat <<EOT
usage: aba relink

Re-link files in the project tree to their equivalent in the revision
library (or in-tree pristine), if they are unchanged.

EOT
}

# extended help for aba command -H or aba help command
cmd_ext_help()
{
echo -n
}	

aba_run "$@"
# arch-tag: relink by Aaron Bentley  (15:25 Feb 06 2004)
