#!/bin/sh
# Copyright (C) 2004 Robin Green
#
# See the file "COPYING" for further information about
# the copyright and warranty status of this work.

. "$abadir/aba-lib"
cmd_exec()
{
# I think it's a good idea to avoid accidentally blowing away wanted changes
  aba_no_changes

# aba_tree_revision doesn't require an archive access
  latest_rev=$(aba_tree_revision)
  latest_ver=$(tla tree-version)

  aba_try tla undo -n $1
  aba_try tla sync-tree $latest_rev
  aba_try tla set-tree-version $latest_ver
}
cmd_desc()
{
  echo '                      revert : reverts tree to the specified revision'
}
cmd_help()
{
    cat <<EOH
reverts tree to the specified revision
usage: $abaname $(basename $0) [version/revision]

This reverts to the specified revision or version while retaining the
patch-logs, so that you can successfully run tla commit afterwards.

EOH
}
cmd_ext_help()
{
    cat <<EOH
EOH
}
aba_run "$@"
# arch-tag: revert by Robin Green (11:14 Mar 26, 2004)
