#! /bin/sh
## Copyright (C) 2004 Aaron Bentley
##
## See the file "COPYING" for further information about
## the copyright and warranty status of this work.

. "$abadir/aba-lib"

# executes the command ("$@" are the arguments after the command name)
cmd_exec()
{
   if [ -z "$1" ]; then
      echo No filename specified
      exit 1
   fi
   if [ ! -f $1 ]; then
     echo "No such file: $1"
     exit
   fi
   aba_break_link $1
   type=$(file -b $1)
   if [ "$type" = "Bourne shell script text executable" ]; then prefix="# ";fi
   if [ "$type" = "ASCII C program text" ] || [ "$type" = "ASCII C++ program text" ]; then
     prefix='/*'
     suffix=' */'
   fi
   who=$(tla my-id|sed -e 's/<.*>//')
   when=$(date '+%H:%M %b %d %Y')
   echo "$prefix arch-tag: $1 by $who ($when)$suffix">> $1
}

# one-liner description for aba help
cmd_desc()
{
  aba_desc tagline adds a new tagline for the given file
}

# short help for aba command -h, --help
cmd_help()
{
   echo usage: aba tagline filename
}

# extended help for aba command -H or aba help command
cmd_ext_help()
{
   echo -n
}	

aba_run "$@"
# arch-tag: tagline by Aaron Bentley  Wed Feb  4 15:56:17 EST 2004
