#! /bin/sh
## Copyright (C) 2004 Jan Hudec
##
## See the file "COPYING" for further information about
## the copyright and warranty status of this work.

. "$abadir/aba-lib"

# executes the command ("$@" are the arguments after the command name)
cmd_exec() {
    test $# -gt 1 && { echo "* Too many arguments"; exit 1; }
    aba_tree_revision "$1"
}

# one-liner description for aba help
cmd_desc()
{
    aba_desc $(basename $0) 'reports the current tree revision name'
}

# short help for aba command -h, --help
cmd_help()
{
    cat <<EOH
This command reports the full revision name of the current tree.
usage: $abaname $(basename $0) [DIR]

EOH
}

# extended help for aba command -H or aba help command
cmd_ext_help()
{
    cat <<EOH
The full name of latest patch from default tree-version in DIR (or current
directory) is printed.

EOH
}	

aba_run "$@"
# arch-tag: c359fe53-673c-423c-9429-30e356d02482
